### ISSUE TITLE
请问如何换成自己的机械臂？

### ISSUE THREAD

**Issue by JinchuanMa** [sychen-sjtu/RRT#1]

**Comment by sychen-sjtu** [comment]
我使用的是MATLAB提供的puma560机械臂，在RRTSmooth.m文件中（在RRT.m中也有代码完全相同的定义），它在109至120行被定义且给定了机械臂参数，p560这个变量就是机械臂，如果你是使用MATLAB提供的方法定义的机械臂的话，删除`mdl_puma560;
p560.links(2).a = 100;
p560.links(3).a = 10;
p560.links(3).d = 20;
p560.links(4).d = 100;`这一行代码（这些代码定义了p560及其参数），然后将代码中的p560这个变量定义为自己的机械臂即可。

**Comment by JinchuanMa** [comment]
> 我使用的是MATLAB提供的puma560机械臂，在RRTSmooth.m文件中（在RRT.m中也有代码完全相同的定义），它在109至120行被定义且给定了机械臂参数，p560这个变量就是机械臂，如果你是使用MATLAB提供的方法定义的机械臂的话，删除`mdl_puma560; p560.links(2).a = 100; p560.links(3).a = 10; p560.links(3).d = 20; p560.links(4).d = 100;`这一行代码（这些代码定义了p560及其参数），然后将代码中的p560这个变量定义为自己的机械臂即可。

您好，很高兴你能回复我，我按你的要求更改，之后会出现如下错误：

错误使用 SerialLink/ikine6s (第 137 行)
This kinematic structure not supported

出错 RRTSmooth (第 132 行)
    q_start=p560.ikine6s(transl(smooth_path(i,:)));
你可以告诉我这是是什么原因导致的吗？

**Comment by sychen-sjtu** [comment]
q_start=p560.ikine6s(transl(smooth_path(i,:)));这行代码是根据机器人末端的位置进行逆运动学求解从而得到机械臂关节的角度，ikine6s是MATLAB给出的robotics工具箱中的函数。你的报错提示你的机器人无法使用这个函数进行你运动学求解，可能是由于你的机器人并非是想puma560这样的六自由度机器人，你可能需要寻找其它求解逆运动学的函数，或者自己推导机械臂的逆运动学的解并在MATLAB中实现。你可以学习并尝试使用ikine()代替ikine6s()进行求解，我并没有使用过这个函数，并不清楚它的适用场景，但它也许会有用。
