### ISSUE TITLE
我想请问一下，您有关于这个设计的文章吗

### ISSUE THREAD

**Issue by 905168041** [sychen-sjtu/RRT#2]
有文章的话，可以方便发一份，希望拜读一下^^

**Comment by sychen-sjtu** [comment]
我主要是参考以下几篇文章实现的，如果想学习的话可以参考一下：
路径规划——改进RRT算法 ：
https://zhuanlan.zhihu.com/p/51087819
RRT算法在三维轨迹规划中的MATLAB仿真： 
https://www.helloworld.net/p/6388284078
RRT路径规划算法：
https://www.guyuehome.com/33685

**Comment by 905168041** [comment]
嗯嗯，十分感谢
